#!/bin/env ruby

require_relative 'color'

`yaourt -Sy --dbpath db`
if 0 == packages = `yaourt -Qu --aur --dbpath db`.chomp.lines.count
    puts green("all packages up to date")
elsif
    puts red("#{packages} packages out of date")
end
