#!/bin/env ruby

require_relative 'color'

`#{`pwd`}/sync`
if 0 == packages = `yaourt -Qu --aur`.chomp.lines.count
    puts green("all packages up to date")
elsif
    puts red("#{packages} packages out of date")
end
